### ISSUE TITLE
Big memory leak in triangulation

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#17]
Currently, due to alignment issues on Windows with std::vector<tetrahedron_t>, it is copied into an array and the pointer to that array (instead of a pointer to the first element of the vector) is passed out through the API.

*Because this array is not deleted, the memory is leaked*.

It might make sense to use something different than the tetrahedron_t struct...

**Comment by FlorianRhiem** [comment]
As advised, this should be fixed by either using a different type or by storing the copy in the Geometry class and letting C++ handle the memory. Storing redundant information may be ugly, but just leaking memory is not an acceptable alternative. Especially not when it happens 60 times per second.

Please check if a std::array<int, 4> solves the alignment issue on Windows, if so this can be used instead of the struct. Otherwise, use an std::vector<int> to store a copy of the data.

**Comment by GPMueller** [comment]
Fixed in commit 5b7ebd3ff25457912230d9ae9fea33e9caa36f07
