### ISSUE TITLE
Desktop GUI needs double-/range-sliders

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#20]
For z-range sliders, double sliders would be nicer than two coupled sliders.

Here is an example implementation: http://stackoverflow.com/a/26025796

**Comment by IngoHeimbach** [comment]
I've tested the implementation provided on stack overflow and got this result:

![screen shot 2016-10-20 at 16 21 39](https://cloud.githubusercontent.com/assets/1449087/19563705/4c0f06de-96e1-11e6-82e4-8b47321f7736.png)

In my opinion, this range slider is not optimal. The blue interval should be drawn between both handles and the second handle should be drawn with the Qt api directly and not using a png file. 

The problem is that this approach tries to customize a normal QSlider. I think, it is necessary to create a custom widget to provide a good solution.

**Comment by GPMueller** [comment]
Implemented range sliders for ui-imgui on the `feature-imgui` branch with a62dd7d2102c47db39667dbaae0784f8c3e1dda7:
![grafik](https://user-images.githubusercontent.com/20167491/103483827-3150d880-4dea-11eb-9459-1761e4dbcda8.png)

Note, range sliders are not yet implemented in ImGui itself, but for my implementation I took inspiration from comments on https://github.com/ocornut/imgui/issues/76.
