### ISSUE TITLE
Feature request: indication of climbing/falling image

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#241]
I think it would make sense to highlight the climbing and falling images in the energy plot. This could be done by choosing different colors for the different image types.

maybe it might also be useful to save the image type in the chain file. with this, one would be able to reload a chain with the proper parameters directly instead of setting the image type again by hand

**Comment by SpiritSuperUser** [comment]
as always, it would be create, if old format files of the chain are still readable when the second feature is implemented

**Comment by GPMueller** [comment]
I will try to implement different markers for different image types:
- cirle = normal
- rectangle = stationary
- triangle (up/down) = climbing/falling
- red marker for current image

Due to the weird way I have to update the chart, the different markers may be jumping around (similar to the jumping around between current image marker (red) and regular (blue).

**Comment by GPMueller** [comment]
Implemented with 0fb4b1b866758c91437544b605bbd13c895c1b5d.
The bug with the jumping dot is removed as well.
