### ISSUE TITLE
output of vacancies

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#258]
If I see this correctly, the output of the vacancies does not make that much sense as vacancies can be set by the setter functions and are therefore written like that to the output file. I would set them to 0 0 0.

**Comment by SpiritSuperUser** [comment]
i was wrong: they are most probably not affected by the setters but the vacancies are affected by the spin torque...

**Comment by GPMueller** [comment]
Implemented with 12ff91d66e188ed22057cabb9c8ac1b2869f9ede:
- when saving configurations, the vacancies will be (0,0,0)
- when reading configurations containing (0,0,0) those spins will become vacancies
- when reading nonzero spins into vacancies, these remain vacancies

Note that the actual spin vectors during a simulation are not set to zero in order to avoid cpu cost and unexpected behaviour (as I did not intend for spin vectors to ever be zero). So care should be taken e.g. when getting the Spins in Python, one should use `geometry.Get_Atom_Types` as well to determine vacancies if needed.
