### ISSUE TITLE
GL: coordinate cross z-axis in HSV map and white background

### ISSUE THREAD

**Issue by GPMueller** [spirit-code/spirit#33]
The axis is hidden when the background and the axis are both white.
Maybe there should be a small (e.g. circular) background behind the coordinate cross in this case? or maybe thicker gray lines placed behind the colored lines?

**Comment by FlorianRhiem** [comment]
As of 98a18534ee9269519df2372bfcd00736f0aacc1f, the coordinate system renderer uses triangle meshes instead of simple lines. This results in white axis arrow on white background looking like this:
![image](https://cloud.githubusercontent.com/assets/4411847/21451731/8afb2560-c901-11e6-97e8-7671f2fca5cc.png)

**Comment by GPMueller** [comment]
Good idea, looks nice!

Currently, the orthographic projection causes the coordinate cross to become distant and react to zoom. Is that a problem of ui-qt?

**Comment by FlorianRhiem** [comment]
No, this was an issue with the combination of a normalized coordinate system and the orthographic projection. It is fixed in VFRendering 0.3.1, which I imported in 8f92d3fcab3824aebab3581c576ca431e3cdd868.

**Comment by GPMueller** [comment]
It is almost fixed now, but the projection is still a bit broken, see #40
