### ISSUE TITLE
Feature request: vacancies in ui

### ISSUE THREAD

**Issue by SpiritSuperUser** [spirit-code/spirit#331]
it would be great if one could define the vacancies directly in the ui in a new "vacancy-mode" by just clicking on the particular spin in the visualization which turns a vacancy on/off

**Comment by GPMueller** [comment]
Geometrically deterimining selected spins etc. could be done analogous to the drag mode (F5 in the UI). The region of selected spins would be a cylinder along the z-axis.
For this, new API functions would be needed which in this case would take a center-point and radius.

Do you have any suggestions for improvements or other ways you would like to be able to do this?

**Comment by SpiritSuperUser** [comment]
I guess this cylinder approach should be fine. 
maybe a square shaped selection by just the normal way of click-hold-move-release would also be good, to allow the selection of geometrically shaped stuff.
the vacancies file should then of course also be saveable (right now you can not load a vacancy file later than at the start, right? this could/should also be implemented).

**Comment by SpiritSuperUser** [comment]
i mean, most convenient would most probable be the selection of any arbitrary shape by just surrounding all meant spins (either free shape or polygon shaped by clicking at the corner points).
But I guess that's a bit too complicated, right?

**Comment by GPMueller** [comment]
I guess the click-hold-move method should work fine and pretty much do what you mean with this polygon (yes that would be too much work) - in the vacancy creation mode you would have a selection area (square or circular), where click and hold would continuously turn any spin inside the selection area into a vacancy, so that you would essentially just cut away parts you do not want.
Since you could also single-click to remove individual spins, this should be enough to easily creaty any desired 2D shape.

**Comment by GPMueller** [comment]
Since 9db0979a63ab28088918613daffe43d2a0329ac5, vacancies can not only be set via the corresponding interactive mode (F6), but also with the configuration settings, such as spherical region etc.
Actually, generally atom types can now be set this way.
