### ISSUE TITLE
Command line options

### ISSUE THREAD

**Issue by MSallermann** [spirit-code/spirit#544]
I think it would be nice to have more command line arguments available. As far as i know, the only one we have currently is `-f` to specify the configuration file, as in

`./spirit -f "path/to/input.cfg"`

Arguments that might be useful:
- `./spirit -i "path/to/image.ovf"` to initialise the system with a given image
- `./spirit -c "path/to/chain.ovf"` to initialise the system with a given chain
- `./spirit --version"` to print the current version
- `./spirit --info` could maybe print information about the scalar type, Cuda/OpenMp, defects enabled etc.

Maybe there are more, that could be useful ...

**Comment by GPMueller** [comment]
- `spirit --version` is a must!
- `spirit --help` should be present in order to get all command line options

Maybe the config file command should be `--cfg` instead of `-f`.

We already have a command line parser, but I would suggest looking into replacing it with [bfgroup/Lyra](https://github.com/bfgroup/Lyra), which is used by [Catch2](https://github.com/catchorg/Catch2/tree/master/third_party).

**Comment by MSallermann** [comment]
Implemented with 2fd1f419dac9ea4cd177baa2fb2ac6f503714b52.
